name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: tests/python-3.12
    runs-on: ubuntu-24.04
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Test
        run: |
          poetry install
          poetry run pytest
