name: Publish to PyPI
on: push
jobs:
  build-and-publish:
    name: build and publish to pypi
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dev requirements
      run: pip install -r dev-requirements.txt
    - name: build
      run: python setup.py sdist bdist_wheel
    - name: publish
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}

