name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: publish/python-3.8
    runs-on: ubuntu-20.04
    services:
      clickhouse:
        image: yandex/clickhouse-server
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.0
        with:
          poetry-version: "1.1.6"
      - name: Test
        run: |
          poetry install
          poetry run pytest
        env:
          TEST_CLICKHOUSE_HOST: clickhouse
      - name: Build
        run: poetry build
      - name: Publish
        env:
          PYPI_TOKEN: $ {{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
