name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: publish/python-3.12
    runs-on: ubuntu-24.04
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Test
        run: |
          poetry install
          poetry run pytest
      - name: Build
        run: poetry build
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          poetry publish
  docs:
    name: docs/python-3.12
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: set up python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Build Docs
        run: |
          poetry install
          poetry run sphinx-build -M html docs/source docs/_build
          touch docs/_build/html/.nojekyll
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_build/html
